
export const app = document.querySelector("#app")
export const manageInventoryBtn = document.querySelector("#manageInventoryBtn")
export const productSideBar = document.querySelector("#productSideBar")
export const closeSideBarBtn = document.querySelector("#closeSideBarBtn")
export const newProductPrice = document.querySelector("#newProductPrice")
export const newProductName = document.querySelector("#newProductName")
export const addNewProductBtn = document.querySelector("#addNewProductBtn")
export const productGroup = document.querySelector("#productGroup")
export const productCartTemplate = document.querySelector("#productCartTemplate")
export const productSelect = document.querySelector("#productSelect")

export const createRecordForm = document.querySelector("#createRecordForm")
export const createRecordFormBtn = document.querySelector("#createRecordFormBtn")
export const recordRowTemplate = document.querySelector("#recordRowTemplate")
export const recordGroup = document.querySelector("#recordGroup")

export const recordTotal = document.querySelector("#recordTotal")
export const recordTax = document.querySelector("#recordTax")
export const recordNetTotal = document.querySelector("#recordNetTotal")
export const checkout = document.querySelector("#checkout")